### ISSUE TITLE
ENH add skglm prox newton solver

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchmark_logreg_l1#30]
@Badr-Moufad has the code to do it; it will require installing skglm from github until we release skglm 0.2

**Comment by Badr-MOUFAD** [comment]
After merging [PR#63](https://github.com/scikit-learn-contrib/skglm/pull/63), ``ProxNewton`` has become the solver used in sparse Logistic Regression (cf. [`estimator.py` diff]( https://github.com/scikit-learn-contrib/skglm/pull/63/files#diff-5a55ebbdbb198f456b4549cc660c2b1e6fc838fd05424e8f4b7775239aed32b9))

We will soon release ``skglm`` v0.2.0, so I think we don't need a PR.

**Comment by mathurinm** [comment]
Yes, but on the other hand using explicitely the prox newton solver will make the code robust to potential future changes in skglm's LogisticRegression

**Comment by Badr-MOUFAD** [comment]
Got you 👌!
